/**
 * Apply Drizzle SQL migrations to a libsql/SQLite database.
 *
 * CLI: `pnpm db:migrate` → `drizzle-kit migrate` (reads drizzle.config.ts).
 * Programmatic (tests): `await applyMigrations(db)`.
 *
 * Migrations live in `./drizzle` (generated by `pnpm db:generate`).
 */

import { migrate } from "drizzle-orm/libsql/migrator";
import path from "node:path";

import type { Db } from "./client";

const DEFAULT_MIGRATIONS_FOLDER = path.join(process.cwd(), "drizzle");

/** Apply all pending migrations from the drizzle/ folder. */
export async function applyMigrations(
  db: Db,
  migrationsFolder: string = DEFAULT_MIGRATIONS_FOLDER,
): Promise<void> {
  await migrate(db, { migrationsFolder });
}
